services:
  api:

    build: .

    container_name: ai-document-api


    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./upload:/app/uploads

    restart: unless-stopped
